[versions]
api-generator = "0.10.1"
binary-compatibility-validator = "0.18.1"
dokka = "2.1.0"
junit = "6.0.2"
kotlin = "2.3.0"
kotlinx-atomicfu = "0.31.0"
kotlinx-datetime = "0.7.1"


[libraries]
# com.gw2tb.api-generator:api-generator - api-generator
# https://github.com/GW2ToolBelt/api-generator
gw2api-generator = { module = "com.gw2tb.api-generator:api-generator", version.ref = "api-generator" }

# org.jetbrains.kotlin - Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

# org.jetbrains.kotlin:kotlin-gradle-plugin  - Kotlin Gradle Plugin
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin ", version.ref = "kotlin" }

# org.jetbrains.kotlinx:kotlinx-datetime - kotlinx-datetime
# https://github.com/Kotlin/kotlinx-datetime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }


[plugins]
# org.jetbrains.dokka - Dokka Gradle Plugin
# https://github.com/Kotlin/dokka
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka" }

# org.jetbrains.kotlin - Kotlin Gradle plugin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# org.jetbrains.kotlinx.atomicfu - kotlinx.atomicfu
# https://github.com/Kotlin/kotlinx-atomicfu
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlinx-atomicfu" }

# org.jetbrains.kotlinx.binary-compatibility-validator - binary-compatibility-validator
# https://github.com/Kotlin/binary-compatibility-validator
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }